### ISSUE TITLE
LunarLander-v2 PPO hyperparams?

### ISSUE THREAD

**Issue by drozzy** [thu-ml/tianshou#442]
I can't seem to get PPO working well on LunarLander.
Has anyone had luck picking good hyperparams for PPO on lunar lander v2?
I tried all these hyperparams and it doesn't seem to want to consistently converge.
<img width="901" alt="Screen Shot 2021-09-07 at 5 09 58 PM" src="https://user-images.githubusercontent.com/140710/132411338-046735d6-f4d4-4d8e-b879-d0558b9dbab3.png">

**Comment by drozzy** [comment]
The "best" hyperparams I found so far is (but these don't consistently give me reward above 0):

```yaml
  buffer-size:
    value: 4096
  repeat-per-collect:
    value: 16
  batch-size:
    value: 8
  steps-per-epoch:
    value: 2_000
  steps-per-collect:
    value: 500
  env-name:
    value: LunarLander-v2    
  max-epoch:
    value: 100
  advantage-normalization:
    value: 0
  activation:
    value: tanh
  recompute-advantage:
    value: 1
  max-grad-norm:
    value: 0
  gae-max-batchsize:
    value: 64
  reward-normalization:
    value: 0
  hidden-sizes:
    value: 64  
```
